[package]
name = "kumarion/timercountdown"
description = "A wrapper for Sleitnick's Timer module that allows you to create a countdown and a timer, with complete tracking to disconnect at any time"
version = "0.0.7"
license = "MIT"
authors = ["Kumarion (https://github.com/Kumarion)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"
Timer = "sleitnick/timer@^1"